version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cfqqwwql
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: apisland/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  backend:
    image: apisland/foodgram:latest
    volumes:
      - ../static_value/:/app/static/
      - ../media_value/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    restart: always
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
