# Generated by Django 2.2.16 on 2022-10-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221009_1527'),
        ('recipes', '0002_auto_20221019_1323'),
    ]

    operations = [
    ]
